### ISSUE TITLE
When AddPath and RTC are both enabled, route withdraw won't be sent.

### ISSUE THREAD

**Issue by kishiguro** [osrg/gobgp#1688] opened 2018-05-21 06:27 UTC
We have one Route Reflector and two Route Reflector Client.
All of peering has VPNv4, AddPath and RTC.

In this condition, VPNv4 route withdraw is not propagated from RR to Client.
Without AddPath, the withdraw are sent and works as expected.

RR Config:
```sh
[global.config]
  as = 1
  router-id = "192.168.55.5"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.55.1"
    peer-as = 1
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "192.168.55.5"
  [neighbors.add-paths.config]
    send-max = 8
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "l3vpn-ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "rtc"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.55.2"
    peer-as = 1
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "192.168.55.5"
  [neighbors.add-paths.config]
    send-max = 8
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "l3vpn-ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "rtc"
```

Client 1 Config:
```sh
[global.config]
  as = 1
  router-id = "192.168.55.1"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.55.5"
    peer-as = 1
  [neighbors.add-paths.config]
    receive = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "l3vpn-ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "rtc"
```

Client 2 Config:
```sh
[global.config]
  as = 1
  router-id = "192.168.55.2"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.55.5"
    peer-as = 1
  [neighbors.add-paths.config]
    receive = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "l3vpn-ipv4-unicast"
 [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
    afi-safi-name = "rtc"
```

In this condition:
At Client 1:

$ gobgp vrf add 1 id 1 rd 111:111 rt both 111:111
$ gobgp vrf 1 rib add 11.11.11.0/24 nexthop 1.1.1.1

At Client 2:
$ gobgp vrf add 1 id 1 rd 111:111 rt both 111:111

Now everybody has 11.11.11.0/24 nexthop 1.1.1.1 in vrf1.
Then At Client 1:

$ gobgp vrf 1 rib del 11.11.11.0/24 nexthop 1.1.1.1

is executed.  The route is withdrawn from Client 1 and RR but not withdrawn from Client 2.
So it keep on having 11.11.11.0/24 in RIB.
I guess is this combination of AddPath and RTC issue.

**Comment by marcin-ptaszynski** [comment] 2018-05-22 04:29
It seems like issue lies in add-path related code:
1. When withdraw is received on RR, it has NLRI only and no attributes.
2. Based on add-path send enabled check executed on RR side: https://github.com/osrg/gobgp/blob/c5fdcad5727dee2411b5e4ad33fd249d3100880d/server/server.go#L991 when processing outgoing paths, we're not using best path from table, which means attrs are still not present.
3. We hit [RTC filtering, because RR matches Ext-Community|https://github.com/osrg/gobgp/blob/c5fdcad5727dee2411b5e4ad33fd249d3100880d/server/server.go#L368] which is not present.

I've created PR #1692 which reproduces the issue in deterministic way.

**Comment by fujita** [comment] 2018-05-23 15:05
Thanks a lot, guys! The following fixes this?
https://github.com/osrg/gobgp/pull/1698

**Comment by marcin-ptaszynski** [comment] 2018-05-23 18:47
@fujita , confirmed that withdraws with add-path/rtc work, thanks a lot!

Although I've noticed that infinite RTC loop #1630 may still happen if RR and Clients have add-path send and receive config, that's https://github.com/osrg/gobgp/pull/1692/files#diff-97d8fb835288c6243f7d0769b1a24a54R113 doesn't work even with the fix for this issue.

Our use-case, though uses send on RR side, but only receive on Client side and this setup doesn't loop.

**Comment by fujita** [comment] 2018-05-23 23:55
@iwaseyusuke can you check if the RTC loop still happen?

**Comment by iwaseyusuke** [comment] 2018-05-24 01:37
Sure.

I tested the version(https://github.com/osrg/gobgp/commit/eb568b68d2522a21ad87c95e427024113aea07dd), but still happened.

RR config:
```toml
[global.config]
  as = 65000
  router-id = "10.0.0.254"

[[peer-groups]]
  [peer-groups.config]
    peer-group-name = "rr-clients"
    peer-as = 65000
  [peer-groups.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "10.0.0.0"
  [peer-groups.add-paths.config]
    send-max = 8
    receive = true
  [[peer-groups.afi-safis]]
    [peer-groups.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
  [[peer-groups.afi-safis]]
    [peer-groups.afi-safis.config]
      afi-safi-name = "rtc"

[[dynamic-neighbors]]
  [dynamic-neighbors.config]
    prefix = "10.0.0.0/24"
    peer-group = "rr-clients"
```

Client1 config:
```toml
[global.config]
  as = 65000
  router-id = "10.0.0.1"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.0.0.254"
    peer-as = 65000
  [neighbors.add-paths.config]
    send-max = 8
    receive = true
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "rtc"
```

With the above config (even if Client2 not started), the RTC loop was occurred when I created a VRF on Client1.
```bash
gobgp vrf add 1 id 1 rd 65000:1 rt both 65000:1
```

**Comment by fujita** [comment] 2018-05-24 01:44
so we hit another rtc bug? https://github.com/osrg/gobgp/pull/1641 was fixed, right?

**Comment by iwaseyusuke** [comment] 2018-05-24 02:09
The following is just my guessing and not confirmed yet though, when Add-Paths enabled, `oldList` is empty:
https://github.com/osrg/gobgp/blob/abefa741b81b833943987f7540284883a48a9ffb/server/server.go#L993-L1005

On the other hand, because we dropped Adj-RIB-Out, I implemented a filtering rule to determine whether the given path is already sent or not by comparing the old path and the new path:
https://github.com/osrg/gobgp/blob/abefa741b81b833943987f7540284883a48a9ffb/server/server.go#L469-L479

So when Add-Path is enabled, the above cannot compare the old path and the new path, and will miss to filter out the already sent path.

**Comment by fujita** [comment] 2018-05-24 02:14
I see, thanks. I'll take care of this. Can you add tests on this and https://github.com/osrg/gobgp/pull/1641?

**Comment by fujita** [comment] 2018-05-27 06:40
Done.

**Closed by fujita** 2018-05-27 06:40 UTC
