### ISSUE TITLE
Route Target Constraints cause infinite UPDATE loop

### ISSUE THREAD

**Issue by marcin-ptaszynski** [osrg/gobgp#1630] opened 2018-04-03 00:16 UTC
When using RR and RR Client configuration, Route Target Constraint advertisements seem to be ignored and all Routes are advertised regardless.

Scenario:
RR: 192.168.80.221
D1: 172.19.0.1 has single VRF with import/export RT 24968:61611 (below .pcapng file originates from this device)
D2: 172.19.0.2 has single VRF with import/export RT 34728:43896

During initial exchange routes from D2 are advertised to D1 even though D1 has sent RTC NLRI for 24968:61611 only. Expected it to be a race during initial exchange, so after ~1 minute I've added another route to D2 VRF and again it was advertised to D1.

Attaching [gobgp-rtc-dont-work.pcapng.zip](https://github.com/osrg/gobgp/files/1869770/gobgp-rtc-dont-work.pcapng.zip)

**Comment by marcin-ptaszynski** [comment] 2018-04-03 00:34
@iwaseyusuke , sorry, I've missed "rtc" safi on D2, which may have caused this. It seems all devices need to enable it.

After adding "rtc" on all Routers, it seems to have initially worked, but then adding VRF on D2 with:

```
root@D2$ gobgp vrf add test2 id 2 rd  24968:61611 rt both  24968:61611
```

caused all BGP instances to loop at 100% CPU.

**Comment by iwaseyusuke** [comment] 2018-04-03 01:43
@marcin-ptaszynski Thanks for reporting!

With the latest master (3645e7dee68faff9bd4fbadbb47dc89ecd06058a), I could reproduce the infinite UPDATE loop.

@marcin-ptaszynski Could you tell me which version you are using?

---

Reproduction scenario

```text
# Topology

              +----+
     +--------| RR |--------+
     |        +----+        |
     |                      |
+---------+            +---------+
| Client1 |            | Client2 |
+---------+            +---------+
```

```toml
# RR

[global.config]
  as = 65000
  router-id = "10.0.0.254"

[[peer-groups]]
  [peer-groups.config]
    peer-group-name = "rr-clients"
    peer-as = 65000
  [peer-groups.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "10.0.0.0"
  [[peer-groups.afi-safis]]
    [peer-groups.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [[peer-groups.afi-safis]]
    [peer-groups.afi-safis.config]
      afi-safi-name = "ipv6-unicast"
  [[peer-groups.afi-safis]]
    [peer-groups.afi-safis.config]
      afi-safi-name = "rtc"

[[dynamic-neighbors]]
  [dynamic-neighbors.config]
    prefix = "10.0.0.0/24"
    peer-group = "rr-clients"
```

```toml
# Client1

[global.config]
  as = 65000
  router-id = "10.0.0.1"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.0.0.254"
    peer-as = 65000
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv6-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "rtc"
```

```toml
[global.config]
  as = 65000
  router-id = "10.0.0.2"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.0.0.254"
    peer-as = 65000
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv6-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "rtc"
```

The UPDATE messages like the following were advertised repeatedly (looks infinite loop).

```text
# Client1 ---> RR
Border Gateway Protocol - UPDATE Message
    Marker: ffffffffffffffffffffffffffffffff
    Length: 76
    Type: UPDATE Message (2)
    Withdrawn Routes Length: 0
    Total Path Attribute Length: 53
    Path attributes
        Path Attribute - ORIGIN: IGP
            Flags: 0x40, Transitive: Well-known, Transitive, Complete
            Type Code: ORIGIN (1)
            Length: 1
            Origin: IGP (0)
        Path Attribute - AS_PATH: empty
            Flags: 0x40, Transitive: Well-known, Transitive, Complete
            Type Code: AS_PATH (2)
            Length: 0
        Path Attribute - LOCAL_PREF: 100
            Flags: 0x40, Transitive: Well-known, Transitive, Complete
            Type Code: LOCAL_PREF (5)
            Length: 4
            Local preference: 100
        Path Attribute - ORIGINATOR_ID: 10.0.0.254 
            Flags: 0x80, Optional: Optional, Non-transitive, Complete
            Type Code: ORIGINATOR_ID (9)
            Length: 4
            Originator identifier: 10.0.0.254
        Path Attribute - CLUSTER_LIST: 10.0.0.0
            Flags: 0x80, Optional: Optional, Non-transitive, Complete
            Type Code: CLUSTER_LIST (10)
            Length: 4
            Cluster List: 10.0.0.0
        Path Attribute - MP_REACH_NLRI
            Flags: 0x80, Optional: Optional, Non-transitive, Complete
            Type Code: MP_REACH_NLRI (14)
            Length: 22
            Address family identifier (AFI): IPv4 (1)
            Subsequent address family identifier (SAFI): Route Target Filter (132)
            Next hop network address (4 bytes)
                Next Hop: 10.0.0.254
            Number of Subnetwork points of attachment (SNPA): 0
            Network layer reachability information (13 bytes)
                MP Reach NLRI 65000:24968:61611/96
                    Prefix Length: 96
                    Originating AS: 65000
                    Community Prefix: 24968:61611

# RR ---> Client1
Border Gateway Protocol - UPDATE Message
    Marker: ffffffffffffffffffffffffffffffff
    Length: 62
    Type: UPDATE Message (2)
    Withdrawn Routes Length: 0
    Total Path Attribute Length: 39
    Path attributes
        Path Attribute - ORIGIN: IGP
            Flags: 0x40, Transitive: Well-known, Transitive, Complete
            Type Code: ORIGIN (1)
            Length: 1
            Origin: IGP (0)
        Path Attribute - AS_PATH: empty
            Flags: 0x40, Transitive: Well-known, Transitive, Complete
            Type Code: AS_PATH (2)
            Length: 0
        Path Attribute - LOCAL_PREF: 100
            Flags: 0x40, Transitive: Well-known, Transitive, Complete
            Type Code: LOCAL_PREF (5)
            Length: 4
            Local preference: 100
        Path Attribute - MP_REACH_NLRI
            Flags: 0x80, Optional: Optional, Non-transitive, Complete
            Type Code: MP_REACH_NLRI (14)
            Length: 22
            Address family identifier (AFI): IPv4 (1)
            Subsequent address family identifier (SAFI): Route Target Filter (132)
            Next hop network address (4 bytes)
                Next Hop: 10.0.0.1
            Number of Subnetwork points of attachment (SNPA): 0
            Network layer reachability information (13 bytes)
                MP Reach NLRI 65000:24968:61611/96
                    Prefix Length: 96
                    Originating AS: 65000
                    Community Prefix: 24968:61611
```

**Comment by marcin-ptaszynski** [comment] 2018-04-03 02:42
Thanks for confirming @iwaseyusuke . I've reproduced this first time using version 7442236025fb2ed80ea2d07e2faff433696727c7  (and I haven't used rtc feature before)

**Comment by iwaseyusuke** [comment] 2018-04-03 02:55
Thanks @marcin-ptaszynski , I will investigate the cause of this issue.

**Comment by iwaseyusuke** [comment] 2018-04-05 23:32
**UPDATE:** I found the cause of this issue.

When GoBGP dropped adj-Rib-out per Peer on this commit(https://github.com/osrg/gobgp/commit/f610dc4422e73f2287dc4b372242d780b484a453#diff-6bb9313653f0c08f070699db6d3a7503R234), we fixed to send the same Route Target Membership (RTM) NLRI even if it is already sent.

With the following topology for example;
```text
     +----- RR -----+
     |              |
  Client1        Client2
```

When Client1 has VRF with RT 65000:1 and sends a RTM NLRI to RR, then RR reflects the NLRI to Client2. If a new VRF with the same RT 65000:1 on Client2 is created, Client2 will notify it to RR, then RR calculates the best, but RR will send the NLRI from Client2 to Client1 even if it is not the best. Client1 receives the NLRI again, calculates the best and re-sends the best (even if sent before). Then, RR reflects the received NLRI ... (infinite loop).

I'm trying to fix this problem now.

**Comment by iwaseyusuke** [comment] 2018-04-09 00:44
@marcin-ptaszynski Hi, I've just created a PR for this issue; https://github.com/osrg/gobgp/pull/1641
Does this PR fix this problem?

**Comment by fujita** [comment] 2018-04-10 05:01
Pushed the fix. Please try the master.

**Closed by fujita** 2018-04-10 05:01 UTC
