### ISSUE TITLE
Error: Missing mandatory attribute: 01

### ISSUE THREAD

**Issue by dbarrosop** [osrg/gobgp#1660] opened 2018-05-02 12:50 UTC
Hello,
if you try to install a path using the grpc interface and you forget to set the Origin field the grpc interface will install it successfully without the attribute set and will advertise that to neighbors causing the neighbors to drop the connection because a mandatory field is missing.

Regards.

**Comment by greenpau** [comment] 2018-05-02 23:31
> to install a path using the grpc interface and you forget to set the Origin field the grpc 

@dbarrosop , what is the command or API call did you use to accomplish the above?

**Comment by dbarrosop** [comment] 2018-05-03 07:47
Sure, should have added it to begin with. This is the function I was playing with (I commented out the origin attribute). Also, note I was trying to understand how to this at this point so I apologize if there is a much better and simpler way :P
  
```
func addPath(c pb.GobgpApiClient, vrf string, nexthop string, id uint32) {
        pattr := make([]bgp.PathAttributeInterface, 0)
        nlri := bgp.NewIPAddrPrefix(24, "10.0.0.0")
        pattr = append(pattr, bgp.NewPathAttributeNextHop(nexthop))
        // pattr = append(pattr, bgp.NewPathAttributeOrigin(0))
        nlri.SetPathIdentifier(id)
        path := table.NewPath(nil, nlri, false, pattr, time.Now(), false)

        r, err := c.AddPath(context.Background(), &pb.AddPathRequest{
                Resource: pb.Resource_VRF,
                VrfId:    vrf,
                Path:     pb.ToPathApi(path),
        })
        if err != nil {
                log.Fatal(err)
        }
        log.Println("path: %v", r)
}
```

**Comment by greenpau** [comment] 2018-05-03 10:33
@dbarrosop , that's why we are in this game :-) Please take a look at this snippet https://github.com/osrg/gobgp/blob/07196197675c07c712eba0c24a934dcbe20783e4/table/destination_test.go#L75 and compare it to the above function. My thinking is that in the above function, the Origin is initialized with zero, because of make allocation. See https://stackoverflow.com/questions/29164375/golang-correct-way-to-initialize-empty-slice?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by greenpau** [comment] 2018-05-03 11:09
@dbarrosop , there is no check for mandatory attributes here: https://github.com/osrg/gobgp/blob/b05e13b4951858524ce81a532c0fa8e2a42b88ba/table/path.go#L156

**Comment by dbarrosop** [comment] 2018-05-03 11:39
Yeah, my point with this issue is that the grpc interface should do one of two things:

1. Reject a route with a mandatory field missing
2. Initialize mandatory fields with a sane default

I am fine either way, but installing an incorrect path and then sending it to neighbors causing an outage is probably not the best way to go.

**Comment by greenpau** [comment] 2018-05-03 14:06
> I am fine either way, but installing an incorrect path and then sending it to neighbors causing an outage is probably not the best way to go.

@dbarrosop , PR is in progress on this one.

**Comment by greenpau** [comment] 2018-05-03 15:41
@dbarrosop , while working on test cases I realized that `NewPath()` is somewhat dangerous. It could lead to things like this:

```
(*table.Path)(0xc4200ea380)((PANIC=runtime error: invalid memory address or nil pointer dereference){
 info: (*table.originInfo)(0xc42006a960)({
  nlri: (bgp.AddrPrefixInterface) <nil>,
  source: (*table.PeerInfo)(<nil>),
  timestamp: (int64) 1524333155,
  validation: (*table.Validation)(<nil>),
  key: (string) "",
  uuid: (uuid.UUID) (len=16 cap=16) 00000000-0000-0000-0000-000000000000,
  noImplicitWithdraw: (bool) false,
  isFromExternal: (bool) false,
  eor: (bool) false,
  stale: (bool) false
 }),
 IsWithdraw: (bool) true,
 pathAttrs: ([]bgp.PathAttributeInterface) <nil>,
 attrsHash: (uint32) 0,
 reason: (table.BestPathReason) Unknown,
 parent: (*table.Path)(<nil>),
 dels: ([]bgp.BGPAttrType) <nil>,
 filtered: (map[string]table.PolicyDirection) {
 },
 VrfIds: ([]uint16) <nil>,
 IsNexthopInvalid: (bool) false
})

```

**Comment by iwaseyusuke** [comment] 2018-05-07 00:12
Excuse me for jumping in,

If adding checks or initialization at `NewPath()` is "dangerous", how about moving it to [`fixupApiPath()`](https://github.com/osrg/gobgp/blob/756cc9162afb675dd7ca159b6f07a6d5b927bcc1/server/server.go#L1269)?

This function will be call like following;
https://github.com/osrg/gobgp/blob/756cc9162afb675dd7ca159b6f07a6d5b927bcc1/server/server.go#L1329-L1342
and this function has the similar modification about some other attributes. I guess we can initialize the mandatory attributes more safer.

**Comment by greenpau** [comment] 2018-05-07 00:25
> If adding checks or initialization at NewPath() is "dangerous", how about moving it to fixupApiPath()?

@iwaseyusuke , I am not sure if it is that dangerous 😄  It panics when `pattrs` is set to `nil`.

> If adding checks or initialization at NewPath() is "dangerous", how about moving it to fixupApiPath()?

@iwaseyusuke , I am still studying this code base. Apologies, but I don't think I have the right to have an opinion about it at the moment. It is like a coding exercise for me right now. I created a PR, made some changes, tracked unit tests, and ... I think I have to redo it from scratch 😄 This `NewPath()` impacts a lot of things, have to be careful.

**Comment by greenpau** [comment] 2018-05-31 01:04
> Yeah, my point with this issue is that the grpc interface should do one of two things:
>    Reject a route with a mandatory field missing
>    Initialize mandatory fields with a sane default

@dbarrosop , I got back to it https://github.com/osrg/gobgp/pull/1663. Here, I add ORIGIN attribute and set it to IGP. Will that be enough to resolve your issue?

**Comment by fujita** [comment] 2018-05-31 11:44
>Reject a route with a mandatory field missing
I prefer this. However, the ability to sending a malformed message might be useful? Actually, I use exabgp for this purpose.

**Comment by dbarrosop** [comment] 2018-05-31 12:04
> @dbarrosop , I got back to it #1663. Here, I add ORIGIN attribute and set it to IGP. Will that be enough to resolve your issue?

That looks good to me although I have no strong opinions about rejecting it or just setting a default value if missing.

> I prefer this. However, the ability to sending a malformed message might be useful? 

Maybe, some alternatives might be:

1. log a warning saying something malformed is about to be sent but that might be risky as the impact of doing it is catastrophic as it tears down the BGP session
2. Have an "expert" or "develop" flag might be a good solution to disable/enable some stuff
3. Have the the RPC call enforce this on the server side and have a different RPC call where this is not enforced.

> Actually, I use exabgp for this purpose.

I don't think you can send a BGP prefix with exabgp with a missing mandatory field. I have written plenty of exabgp code in the past and I don't recall ever having to specify the origin :P

**Comment by fujita** [comment] 2018-05-31 12:54
I created a pr to reject a route without an origin attribute. Once the CI finishes, I'll push it. I'll think about sorta expert flag after the next release, I'll plan to change the AddPath API, as discussed on the different issue anyway.

> I don't think you can send a BGP prefix with exabgp with a missing mandatory field. I have written plenty of exabgp code in the past and I don't recall ever having to specify the origin 📦 

Oops, I meant the malformed message in general. I did something like the following with exabgp:

```
  static {
    # malformed AS_PATH
    route 10.7.0.2/32 next-hop 10.0.255.7 attribute [ 0x02 0x60 0x11223344 ];
  }

**Comment by greenpau** [comment] 2018-05-31 13:37
@dbarrosop , @fujita , by and large, the issue is interoperability with other BGP software.

Although the common sense says "Reject a route with a mandatory field missing", the practical aspect of it is that non-compliant prefixes will be rejected and the prefixes will not be propagated. At the end, reachability issues. ORIGIN incomplete

Currently, there is no enforcement. I tend to agree with @dbarrosop when he says:

> Have an "expert" or "develop" flag might be a good solution to disable/enable some stuff

For example, `--strict` option would enable the checks.

The other unrelated practicality of it is that there are multiple tests invoking `NewPath` 😄 Some of them do not pass BGP attributes. I tracked them all down at some point. Then, I asked myself "was it worth it"? ;-) It was from a learning perspective, but then I wondered about the interoperability.

What is better for this project: strict compliance vs. greater interoperability?

**Comment by dbarrosop** [comment] 2018-05-31 15:02
> The other unrelated practicality of it is that there are multiple tests invoking NewPath 😄 Some of them do not pass BGP attributes

I think it's good you tracked them down and if the project decides to implement the `--strict` mode it'd be good to run the tests both fixed and not fixed using both the flag or not to properly test the behavior. So your fixed tests should always pass while the previous ones should break in the strict mode while pass in the non-strict mode.

> What is better for this project: strict compliance vs. greater interoperability?

My personal opinion, even though, I am not part of the project, is that gobgp is very interesting from a developer perspective as a replacement for exabgp so I think both are important. So I'd vote for enforcing by default and have a developer flag or different RPC calls to give more power to the developer. I also understand this adds overall complexity to the project and that it might not be worth it.

**Comment by fujita** [comment] 2018-06-01 00:01
I don't want to support '--strict' option in the CLI but I plan to add such to the GRPC API.

**Closed** 2018-06-01 00:02 UTC
